### ISSUE TITLE
Make REPL more obvious

### ISSUE THREAD

**Issue by daurnimator** [fengari-lua/fengari.io#2]
A few people have told me that it's not obvious that there is a REPL.

I was thinking of pre-filling the repl with something like:

```lua
table.concat({"This is a Lua REPL", "You can use the 'js' library to interoperate with the browser.", 'e.g. try: require "js".global:alert("Hello from Lua!")'}, "\n")
```

**Comment by giann** [comment]
Yes we can do that. I also added the focus on the input field so it's a little more obvious than before.

**Comment by daurnimator** [comment]
A simpler solution might be to add a `<h2>Try it out in the REPL</h2>`
